davrodpin/mole

tunnel/config.go
tunnel/tunnel.go

This change renames the structs and functions that were using the verb
'resolve' to ssh-related entities like SSHFileCofnig and SSHHost to
better communicate what they really represent.

Renaming Resolver to SSHFileConfig

---

cli/cli.go

This changes fix the issue where the cli was invalidating commands other
than `new-aliases`.

Fix cli validation

---

cli/cli.go
cli/cli_test.go
cmd/mole/main.go

Return error when required flag is missing

---

cli/cli.go
tunnel/config.go
tunnel/tunnel.go

Use LocalForward option from SSH config file when local and remote options are absent #13

Use LocalForward option from SSH config file 

---

Makefile

This change adds a new safe guard to fail tests if the code is not
formatted using 'go fmt'.

Fail build if code is not formatted

---

tunnel/config.go
tunnel/config_test.go

This change fixes the warning messages related to bad `LocalForward`
parsing from $HOME/.ssh/config.
Closes: #42

Fix warn log messages related to LocalForward

---

cli/cli.go
cli/cli_test.go

This change extends the list of supported characters on the given server
name.
Closes: #49

Fix unsupported characters on server name

---

cli/cli.go
cmd/mole/main.go
test-env/README.md
tunnel/tunnel.go
tunnel/tunnel_test.go

Add an insecure mode where `mole` will skip the validation of host keys before connecting to the  ssh server

Insecure mode

---

README.md

This change remove the badges from the README.md since all quality
checks will not be made through Github Actions.

Remove third-party integrations

---

.github/actions/report/Dockerfile
.github/actions/report/README.md
.github/actions/report/entrypoint.sh
.github/actions/syntax/README.md
.github/actions/syntax/entrypoint.sh
.github/actions/test/Dockerfile
.github/actions/test/README.md
.github/actions/test/entrypoint.sh
.github/main.workflow

This change adds the code coverage diff between the current and previous
commits. The numbers are getting printed to the standard output.

Report coverage diff from previous commit

---

.github/actions/report/entrypoint.sh
.github/main.workflow

This change moves the coverate report archive to dropbox instead of the
source code repository itself.

Change the cov. report repo to dropbox

---

.gitignore
Makefile
cmd/mole/main.go
storage/storage.go
storage/storage_test.go
tunnel/config.go
tunnel/tunnel.go
tunnel/tunnel_test.go

This change modifies how the user home directory is retrieved to use
`os.HomeUserDir()` which is suppported on different platforms (e.g. mac,
linux, windows)
Closes #47

Add support for Windows

---

cli/cli.go
cmd/mole/main.go
test-env/README.md
test-env/ssh-server/sshd_config
tunnel/tunnel.go
tunnel/tunnel_test.go

This change adds a mechanism to keep idle tunnels active even if the ssh
server is configured to end any connections that is idle for a period of
time by sending a global ssh request with no data.
Refers-to: #24, #26

Keep SSH connection alive

---

cmd/mole/main.go
go.mod
go.sum

See https://github.com/satori/go.uuid/issues/84 detailing issues with the go.uuid package. It's apparently no longer maintained and has [serious issues](https://github.com/satori/go.uuid/issues/73) in its random capabilities.
Switched to using the community fork https://github.com/gofrs/uuid

Use community fork of uuid package

---

test-env/README.md
test-env/ssh-server/Dockerfile
test-env/ssh-server/supervisord.conf

This change adds supervisor to the container that runs the ssh server, so
it can be restarted without a need to re-run the container.

Make ssh server of test-env manageable

---

cli/cli.go
cmd/mole/alias.go
cmd/mole/main.go
storage/storage.go

This change fixes a bug where creating an alias passing the -insecure
flag would not trigger the persistence of that option in
`$HOME/.mole.conf`.
Closes: #89

Fix persistence of insecure mode

---

cli/cli.go
cmd/mole/alias.go
cmd/mole/main.go
storage/storage.go
tunnel/tunnel.go

Close #12 
Signed-off-by: Ricardo Seriani <ricardo.seriani@gmail.com>

Add timeout parameter

---

cmd/mole/main.go

For https://github.com/davrodpin/mole/issues/86
Adds some basic validation of the remote address(es). The program will now exit with an error message if an address does not contain ":<port-number>".
Let me now if it was what you had in mind, or if I should change something.

Add validation of -remote flag

---

cli/cli.go
cmd/mole/main.go
test-env/README.md
tunnel/tunnel.go
tunnel/tunnel_test.go

This change improves the resilience of mole by adding a connection retry
mechanism when the ssh connection is closed by any unexpected reason.
The number of retries and the wait time between retries are configurable
through the `-connection-retries` and `-retry-wait` flags.
Closes: #24

Add retries if ssh conn shuts down

---

README.md

Since the minimal version of this project is now Go 1.13, the project can now be imported in the GOPATH and still use the go modules to manage it's dependency,even if the environment variable GO111MODULE=auto (which is the default), as stated in https://golang.org/doc/go1.13#modules
Signed-off-by: Ricardo Seriani <ricardo.seriani@gmail.com>

Fix README.md message about using go modules.

---

docs/index.md

You can now install mole using [MacPorts](https://macports.org).  Updating documentation on how.

Update documentation on installing via MacPorts

---

cli/cli.go
cmd/mole/alias.go
cmd/mole/main.go
go.sum
storage/storage.go
tunnel/config.go
tunnel/example_test.go
tunnel/tunnel.go
tunnel/tunnel_test.go

An ssh-agent started in the traditional way (eval $(ssh-agent)) sets an
environment variable SSH_AUTH_SOCK which points to a unix socket that
the agent listens to. If that environment variable is set add the public
keys in the ssh agent to the list of keys used during authentication.
closes #87

ssh-agent support

---

Makefile

I'm not sure what your process is for uploading releases to GH, but this patch adds cross building for arm arch via the go toolchain to your `bin` target.

Add arm builds

---

.github/actions/check/Dockerfile

This change updates the docker image used for continuous integration, updating
the Go version to 1.14.

Update CI docker image

---

Makefile
alias/alias.go
alias/alias_test.go
cmd/add_alias.go
cmd/root.go
cmd/start_local.go
cmd/start_remote.go
go.mod
go.sum
test-env/README.md
test-env/http-server/Dockerfile
test-env/ssh-server/Dockerfile
tunnel/config.go
tunnel/config_test.go
tunnel/example_test.go
tunnel/key_test.go
tunnel/tunnel.go
tunnel/tunnel_test.go

This change adds support for a new type of ssh tunnel, the [remote port forwarding](https://www.ssh.com/ssh/tunneling/example#remote-forwarding).
Partially implements #22.

 Add support for ssh remote port forwarding

---

alias/alias.go
alias/alias_test.go
cmd/root.go
cmd/start_alias.go
cmd/start_local.go

This change allows the user to provide certain flags to `start alias`
command. The flags provided through CLI will override the ones stored in
the alias configuration.
Fixes #119.

Add flags to "start alias" command

---

.github/actions/check/entrypoint.sh

This change removes the coverage reports that were published on dropbox.
All coverage stats are already part of the CI job output.

Remove cov diff report

---

cmd/root.go
main.go

This change makes the log module configuration and memguard destrutor
call to be initialized only once and in the right place.

Remove duplication of log and memguard init.

---

alias/alias.go
alias/alias_test.go
cmd/root.go

This change fixes the issue with the `verbose`, `insecure` and
`detach` flags being saved with value true bue  not working when using the
`start alias` command.
Closes #127

Fix load value of certain flags from alias

---

alias/alias.go
alias/alias_test.go
cmd/root.go
tunnel/config.go
tunnel/example_test.go
tunnel/tunnel.go
tunnel/tunnel_test.go

You can now pass SSH config file path as a --config flag parameter.

SSH config file path flag parameter

---

alias/alias_test.go
alias/testdata/example.toml
alias/testdata/test-env.toml

This change fixes the issue with test setup where some files are copied to
`TMPDIR` and a "invalid cross-device link" error is raised, which
happens when a file is moved to different partitions.

Fix copy of files to different partitions

---

alias/alias.go
alias/alias_test.go
alias/testdata/example.toml
alias/testdata/show.alias.fixture
alias/testdata/show.alias.test-env.fixture
alias/testdata/test-env.toml
cmd/root.go
fsutils/fsutils.go
go.mod
go.sum
mole/app.go
mole/app_test.go
mole/mole.go
mole/mole_test.go
rpc/doc.go
rpc/rpc.go
rpc/rpc_test.go

This change introduces a remote procedure call server responsible for
handling requests to execute pre-registered procedures using JSON-RPC
2.0 as the transport protocol.
The rpc server is disable by default. The user can enable it through the
`--rpc` flag. By default, the server will be listening on the localhost
address and on a random free port since a user might have multiple
instance of the program running at the same time on a single machine.
The `--rpc-address` flag can be use to set a specific address.

Add a rpc server

---

rpc/rpc.go
rpc/rpc_test.go

This change adds parameters to the functions that can be called
remotely.

Add support for parameters on rpc

---

cmd/start_alias.go

This change fixes the issue where passing a flag while calling `mole
start alias <alias>` is ignored by the program.

Fix start alias flag parsing

---

cmd/stop.go
fsutils/fsutils.go
fsutils/fsutils_test.go
mole/app.go
mole/app_test.go
mole/mole.go

This change makes sure that both foreground and background (detached)
mole instances will have a correspoding pid file located on
`$HOME/.mole`, which is mainly needed to allows users to stop foreground
instances using the `stop` command.
Since foreground instances are considered ephemeral, the code will
remove the directory associated with that instance (i.e.
`$HOME/.mole/<id>` once the instances stops for whatever reason.
Also, this change makes the foreground instance identifier to be a
random string (out of a uuid4) instead of the process number.

Add pid file for any kind of instance

---

mole/mole.go
mole/rpc.go
mole/runtime.go
tunnel/tunnel.go

This change makes the runtime information to return the addresses used
by the ssh channels instead of the input.

Return resolved addresses

---

tunnel/tunnel.go

This change makes the connection to the ssh server and channels setup to
happen in a goroutine when mole is trying to reconnect.
The reason for this change is to allow the tunnel to be closed while the
attemp to reconnect is still in progress.

Execute reconnection on a goroutine
